# Generated by Django 5.2.5 on 2026-08-26 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('leader', 'Leader'), ('operator', 'Operator'), ('engineer', 'Engineer'), ('supervisor', 'Supervisor'), ('admin', 'Admin')], default='operator', max_length=20),
        ),
    ]
