# Generated by Django 5.2.5 on 2026-08-27 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_userprofile_employee_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='employee_number',
            field=models.CharField(blank=True, help_text='Used to generate default password (Name + Employee Number).', max_length=20, null=True, unique=True),
        ),
    ]
