# Generated by Django 6.0.4 on 2026-05-04 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subprocess',
            options={'verbose_name': 'Sub Process', 'verbose_name_plural': 'Sub Processes'},
        ),
        migrations.AlterModelOptions(
            name='workcenter',
            options={'verbose_name': 'Work Center', 'verbose_name_plural': 'Work Centers'},
        ),
    ]
