# Generated by Django 6.0.2 on 2026-05-20 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_subprocess_options_alter_workcenter_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subprocess',
            name='process_type',
            field=models.CharField(choices=[('normal', 'Normal'), ('winding', 'Winding'), ('braze', 'Braze'), ('wind_braze', 'Wind/Braze')], max_length=20),
        ),
    ]
