# Generated by Django 6.0.2 on 2026-05-22 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_shift'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift',
            name='code',
            field=models.CharField(help_text='Short identifier, e.g. DAY, AFT, NGT', max_length=20, unique=True),
        ),
    ]
