# Generated by Django 5.2.5 on 2026-05-24 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_shift_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='days_of_week',
            field=models.JSONField(blank=True, default=list, help_text='Días de la semana: 0=Lunes, 1=Martes … 6=Domingo'),
        ),
    ]
