# Generated by Django 5.2.5 on 2026-05-25 01:51

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_shift_days_of_week'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubProcessType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre del tipo')),
                ('applies_to', models.CharField(choices=[('reactores', 'Reactores'), ('reactores_filtros', 'Reactores-Filtros')], max_length=30, verbose_name='Aplica para')),
                ('units_per_piece', models.PositiveIntegerField(default=1, help_text='Cuántas unidades se necesitan para completar 1 pieza. Ej: si 3 unidades = 1 pieza, escribe 3.', verbose_name='Contador de unidades por pieza')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Subprocess Type',
                'verbose_name_plural': 'Subprocess Types',
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='subprocess',
            name='process_type',
        ),
        migrations.AddField(
            model_name='subprocess',
            name='subprocess_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subprocesses', to='core.subprocesstype', verbose_name='Tipo de subprocess'),
        ),
    ]
