# Generated by Django 5.2.5 on 2026-08-27 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_subprocesstype_remove_subprocess_process_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subprocess',
            name='created_by_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='subprocess',
            name='updated_by_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='workcenter',
            name='created_by_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='workcenter',
            name='updated_by_name',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
