# Generated by Django 6.0.4 on 2026-05-04 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('planning', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LossReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='HourlyExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actual_quantity', models.IntegerField()),
                ('scrap_quantity', models.IntegerField()),
                ('hourly_plan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='planning.hourlyplan')),
            ],
        ),
        migrations.CreateModel(
            name='ExecutionLossReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('execution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.hourlyexecution')),
                ('loss_reason', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.lossreason')),
            ],
        ),
    ]
