# Generated by Django 5.2.5 on 2026-05-19 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='executionlossreason',
            options={'verbose_name': 'Execution Loss Reason', 'verbose_name_plural': 'Execution Loss Reasons'},
        ),
        migrations.AlterModelOptions(
            name='hourlyexecution',
            options={'verbose_name': 'Hourly Execution'},
        ),
        migrations.AlterModelOptions(
            name='lossreason',
            options={'verbose_name': 'Loss Reason', 'verbose_name_plural': 'Loss Reasons'},
        ),
    ]
