# Generated by Django 6.0.2 on 2026-05-20 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0002_alter_executionlossreason_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lossreason',
            options={'ordering': ['name'], 'verbose_name': 'Loss Reason', 'verbose_name_plural': 'Loss Reasons'},
        ),
        migrations.AddField(
            model_name='hourlyexecution',
            name='comments',
            field=models.TextField(blank=True, default='', verbose_name='Comentarios / Observaciones'),
        ),
        migrations.AddField(
            model_name='lossreason',
            name='is_default',
            field=models.BooleanField(default=True, help_text='Razón predefinida visible en el formulario'),
        ),
    ]
