# Generated by Django 5.2.5 on 2026-05-21 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0003_alter_lossreason_options_hourlyexecution_comments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hourlyexecution',
            name='over_comments',
            field=models.TextField(blank=True, default='', verbose_name='Overproduction comment'),
        ),
        migrations.AddField(
            model_name='hourlyexecution',
            name='scrap_comments',
            field=models.TextField(blank=True, default='', verbose_name='Scrap comment'),
        ),
        migrations.AlterField(
            model_name='hourlyexecution',
            name='comments',
            field=models.TextField(blank=True, default='', verbose_name='Loss reason comment'),
        ),
    ]
