# Generated by Django 5.2.5 on 2026-05-24 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0004_hourlyexecution_over_comments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hourlyexecution',
            name='ok_comments',
            field=models.TextField(blank=True, default='', verbose_name='Satisfactory comment'),
        ),
    ]
