# Generated by Django 5.2.5 on 2026-05-28 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0005_hourlyexecution_ok_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='hourlyexecution',
            name='zero_comment',
            field=models.TextField(blank=True, default='', help_text='Optional manual note when both planned and actual are 0.', verbose_name='Non-productive hour comment'),
        ),
        migrations.AlterField(
            model_name='hourlyexecution',
            name='actual_quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='hourlyexecution',
            name='scrap_quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='lossreason',
            name='is_default',
            field=models.BooleanField(default=True),
        ),
    ]
