# Generated by Django 5.2.5 on 2026-07-01 22:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0006_hourlyexecution_zero_comment_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('icon', models.CharField(default='fa-circle-info', help_text="Font Awesome icon class suffix, e.g. 'fa-utensils'.", max_length=40)),
                ('color', models.CharField(default='slate', help_text="Tailwind color name used for badges/cards, e.g. 'amber', 'blue'.", max_length=20)),
                ('requires_comment', models.BooleanField(default=False, help_text='If checked, a comment is mandatory whenever this event type is used.', verbose_name='Comment required')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Event Type',
                'verbose_name_plural': 'Event Types',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ExecutionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration_minutes', models.PositiveIntegerField()),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('event_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='executions', to='production.eventtype')),
                ('execution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='production.hourlyexecution')),
            ],
            options={
                'verbose_name': 'Execution Event',
                'verbose_name_plural': 'Execution Events',
                'ordering': ['created_at'],
            },
        ),
    ]
