# Generated by Django 5.2.5 on 2026-07-09 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0008_seed_event_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='hourlyexecution',
            name='auto_categories',
            field=models.CharField(blank=True, default='', help_text='Comma-joined category codes for dashboard filtering (lunch, preop, workfin, chair, extra).', max_length=120, verbose_name='Time Blocks categories (auto)'),
        ),
        migrations.AddField(
            model_name='hourlyexecution',
            name='auto_reason',
            field=models.TextField(blank=True, default='', help_text='Auto-generated from planning Time Blocks. Not a human comment.', verbose_name='Time Blocks summary (auto)'),
        ),
    ]
