# Generated by Django 5.2.5 on 2026-07-09 22:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0011_dailyplan_operator_hourlyplan_operator_and_more'),
        ('production', '0009_hourlyexecution_auto_categories_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(help_text="Stable machine code, e.g. 'lunch'. Never localized.", max_length=30, unique=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('is_planned', models.BooleanField(default=False, help_text='If checked, time in this category is planned/scheduled downtime (e.g. lunch); otherwise it is unplanned.', verbose_name='Counts as planned downtime')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Event Category',
                'verbose_name_plural': 'Event Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='executionevent',
            name='source',
            field=models.CharField(choices=[('manual', 'Manual entry'), ('block', 'Auto-generated from Time Block')], default='manual', help_text='Whether this event was entered manually or generated automatically from a planning Time Block.', max_length=10),
        ),
        migrations.AddField(
            model_name='executionevent',
            name='source_block',
            field=models.OneToOneField(blank=True, help_text='The Time Block that generated this event, if any.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='generated_event', to='planning.hourlyplanblock'),
        ),
        migrations.AddIndex(
            model_name='executionevent',
            index=models.Index(fields=['event_type'], name='production__event_t_91f34f_idx'),
        ),
        migrations.AddIndex(
            model_name='executionevent',
            index=models.Index(fields=['source'], name='production__source_f0e628_idx'),
        ),
        migrations.AddIndex(
            model_name='executionevent',
            index=models.Index(fields=['created_at'], name='production__created_7875a9_idx'),
        ),
        migrations.AddIndex(
            model_name='eventcategory',
            index=models.Index(fields=['code'], name='production__code_dad0b5_idx'),
        ),
        migrations.AddField(
            model_name='eventtype',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Canonical category this event type rolls up to for reporting.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='event_types', to='production.eventcategory'),
        ),
    ]
