# Generated by Django 5.2.5 on 2026-07-16 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0010_eventcategory_executionevent_source_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='executionevent',
            name='user_modified',
            field=models.BooleanField(default=False, help_text='True once a human edited this event; blocks the auto-sync from a planning Time Block from overwriting it.'),
        ),
    ]
