# Generated by Django 5.2.5 on 2026-07-23 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0011_executionevent_user_modified'),
    ]

    operations = [
        migrations.AddField(
            model_name='hourlyexecution',
            name='actual_headcount',
            field=models.IntegerField(blank=True, help_text='People who actually worked this hour. Blank = not captured.', null=True),
        ),
        migrations.AddField(
            model_name='hourlyexecution',
            name='headcount_comment',
            field=models.TextField(blank=True, default='', help_text='Required when the actual headcount differs from the plan.'),
        ),
    ]
