# production/block_bridge.py
# ─────────────────────────────────────────────────────────────────────────────
# Bridge: planning Time Blocks  →  production Operational Events
#
# The spec requires that selecting a System Time Block automatically creates
# the corresponding Operational Time Event, with no manual re-entry. This
# module holds that business logic (kept out of signals/views per SOLID), so
# it can be unit-tested and reused from a data migration, a management
# command, or the admin.
#
# Design notes
#   • Idempotent: each HourlyPlanBlock owns at most ONE ExecutionEvent, linked
#     by ExecutionEvent.source_block (OneToOne). Re-saving a block updates its
#     event instead of duplicating.
#   • Normalized: the event inherits ALL context (date, shift, work center,
#     model, operator) by FK through execution→hourly_plan→daily_plan. Nothing
#     is copied as text.
#   • Category-driven: the block's category code (lunch/preop/…) is matched to
#     an EventCategory, and from there to a representative EventType, so the
#     dashboard's 'Events per Category' works with zero string parsing.
# ─────────────────────────────────────────────────────────────────────────────

from django.db import transaction

# Fallback map from a planning block_type code to the EventType name we seed
# for it. Only used to pick a representative EventType when the category has
# more than one; the authoritative link is EventType.category.
BLOCK_CODE_TO_EVENT_TYPE_NAME = {
    "lunch":   "Lunch",
    "preop":   "Operation Preparation",
    "workfin": "Work Finalization",
    "chair":   "Chair Time",
    "extra":   "Extra Reason",
}


def _resolve_event_type(block):
    """Pick the EventType a block should map to, preferring the one whose
    Category.code matches the block's category code."""
    from .models import EventType, EventCategory

    code = block.category()  # lunch / preop / workfin / chair / extra
    # 1) Prefer an EventType whose category.code matches exactly.
    et = (EventType.objects
          .filter(is_active=True, category__code=code)
          .order_by("order", "name")
          .first())
    if et:
        return et
    # 2) Fall back to a same-named EventType (seeded catalog).
    name = BLOCK_CODE_TO_EVENT_TYPE_NAME.get(code)
    if name:
        et = EventType.objects.filter(is_active=True, name=name).first()
        if et:
            return et
    # 3) Last resort: the catch-all "Other" type.
    return EventType.objects.filter(is_active=True, name="Other").first()


def _get_or_create_execution_for_block(block):
    """Find the HourlyExecution that this block's slot belongs to, creating a
    stub execution if the hour exists but hasn't been captured yet. Returns
    None when there is no matching HourlyPlan hour for the slot (nothing to
    attach the event to)."""
    from planning.models import HourlyPlan
    from .models import HourlyExecution

    hp = (HourlyPlan.objects
          .filter(daily_plan=block.daily_plan, hour=block.slot_time)
          .order_by("id")
          .first())
    if hp is None:
        return None
    execution, _ = HourlyExecution.objects.get_or_create(hourly_plan=hp)
    return execution


@transaction.atomic
def sync_event_for_block(block):
    """Create or update the single ExecutionEvent generated by `block`.
    Idempotent. Returns the ExecutionEvent, or None if it couldn't be placed
    (no matching hour) — in which case any stale generated event is removed."""
    from .models import ExecutionEvent

    execution = _get_or_create_execution_for_block(block)
    if execution is None:
        ExecutionEvent.objects.filter(source_block=block).delete()
        return None

    event_type = _resolve_event_type(block)
    if event_type is None:
        return None

    event = ExecutionEvent.objects.filter(source_block=block).first()
    if event is None:
        event = ExecutionEvent(source_block=block)
    elif event.user_modified:
        # The user has edited this event — their execution record is the
        # source of truth now. Only keep the link/type in sync with the plan,
        # but never overwrite their duration or comment.
        event.event_type = event_type
        event.source     = ExecutionEvent.SOURCE_BLOCK
        event.save(update_fields=["event_type", "source"])
        return event

    event.execution        = execution
    event.event_type       = event_type
    event.duration_minutes = max(0, int(block.minutes or 0))
    event.comment          = block.reason or ""
    event.source           = ExecutionEvent.SOURCE_BLOCK
    if event.created_by_id is None:
        event.created_by = block.created_by
    event.save()
    return event


def remove_event_for_block(block_pk):
    """Delete the event generated by a block that is being deleted."""
    from .models import ExecutionEvent
    ExecutionEvent.objects.filter(source_block_id=block_pk).delete()