# Generated by Django 6.0.4 on 2026-05-04 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('conversion_factor', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='DailyPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('headcount', models.IntegerField()),
                ('shift_start_time', models.TimeField()),
                ('shift_end_time', models.TimeField()),
                ('subprocess', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.subprocess')),
                ('work_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.workcenter')),
            ],
        ),
        migrations.CreateModel(
            name='HourlyPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hour', models.TimeField()),
                ('planned_quantity', models.IntegerField()),
                ('daily_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planning.dailyplan')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planning.model')),
            ],
        ),
        migrations.CreateModel(
            name='Traveler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('traveler_number', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('due_date', models.DateField()),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planning.model')),
            ],
        ),
        migrations.AddField(
            model_name='dailyplan',
            name='traveler',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='planning.traveler'),
        ),
    ]
