# Generated by Django 5.2.5 on 2026-05-19 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailyplan',
            options={'verbose_name': 'Daily Plan'},
        ),
        migrations.AlterModelOptions(
            name='hourlyplan',
            options={'verbose_name': 'Hourly Plan'},
        ),
        migrations.AlterModelOptions(
            name='model',
            options={'verbose_name': 'Model'},
        ),
        migrations.AlterModelOptions(
            name='traveler',
            options={'verbose_name': 'Traveler'},
        ),
        migrations.RemoveField(
            model_name='traveler',
            name='due_date',
        ),
        migrations.RemoveField(
            model_name='traveler',
            name='model',
        ),
        migrations.RemoveField(
            model_name='traveler',
            name='quantity',
        ),
        migrations.AlterField(
            model_name='traveler',
            name='traveler_number',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
