# Generated by Django 6.0.2 on 2026-05-20 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0002_alter_dailyplan_options_alter_hourlyplan_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hourlyplan',
            options={'ordering': ['hour'], 'verbose_name': 'Hourly Plan'},
        ),
        migrations.RemoveField(
            model_name='model',
            name='conversion_factor',
        ),
    ]
