# Generated by Django 5.2.5 on 2026-05-20 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0003_alter_hourlyplan_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailyplan',
            name='traveler',
        ),
        migrations.DeleteModel(
            name='Traveler',
        ),
    ]
