# Generated by Django 6.0.2 on 2026-05-21 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_shift'),
        ('planning', '0004_remove_dailyplan_traveler_delete_traveler'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailyplan',
            name='shift_end_time',
        ),
        migrations.RemoveField(
            model_name='dailyplan',
            name='shift_start_time',
        ),
        migrations.AddField(
            model_name='dailyplan',
            name='shift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='daily_plans', to='core.shift', verbose_name='Shift'),
        ),
    ]
