# Generated by Django 6.0.2 on 2026-05-22 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_shift'),
        ('planning', '0005_remove_dailyplan_shift_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hourlyplan',
            name='is_overtime',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name='dailyplan',
            unique_together={('date', 'subprocess', 'shift')},
        ),
    ]
