# Generated by Django 5.2.5 on 2026-05-24 23:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_shift_days_of_week'),
        ('planning', '0006_hourlyplan_is_overtime_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='model',
            options={'ordering': ['name'], 'verbose_name': 'Model'},
        ),
        migrations.AddField(
            model_name='hourlyplan',
            name='comments',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='hourlyplan',
            name='headcount',
            field=models.IntegerField(blank=True, help_text='Override del headcount para esta hora', null=True),
        ),
        migrations.AlterField(
            model_name='dailyplan',
            name='shift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='daily_plans', to='core.shift'),
        ),
        migrations.AlterField(
            model_name='hourlyplan',
            name='daily_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hourly_plans', to='planning.dailyplan'),
        ),
        migrations.AlterField(
            model_name='model',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.CreateModel(
            name='HeadcountAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_value', models.IntegerField()),
                ('new_value', models.IntegerField()),
                ('comment', models.TextField()),
                ('modified_at', models.DateTimeField(auto_now_add=True)),
                ('daily_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hc_audits', to='planning.dailyplan')),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Headcount Audit',
                'ordering': ['-modified_at'],
            },
        ),
        migrations.CreateModel(
            name='HourlyPlanBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_time', models.TimeField(help_text='Hora de inicio del slot (HH:MM)')),
                ('block_type', models.CharField(choices=[('lunch', 'Lunch Break'), ('preop', 'Pre-Operation Preparation'), ('workfin', 'Work Finalization'), ('chair', 'Chair Time'), ('extra', 'Extra Reason')], max_length=20)),
                ('minutes', models.IntegerField(default=0)),
                ('reason', models.CharField(blank=True, help_text="Para tipo 'extra': descripción manual", max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('daily_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='planning.dailyplan')),
            ],
            options={
                'verbose_name': 'Hourly Plan Block',
                'ordering': ['slot_time', 'created_at'],
            },
        ),
    ]
