# Generated by Django 5.2.5 on 2026-05-25 16:29

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0007_alter_model_options_hourlyplan_comments_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyplan',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='dailyplan',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plans_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dailyplan',
            name='created_by_name',
            field=models.CharField(blank=True, help_text='Username snapshot at creation.', max_length=150),
        ),
        migrations.AddField(
            model_name='dailyplan',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='dailyplan',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plans_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dailyplan',
            name='updated_by_name',
            field=models.CharField(blank=True, help_text='Username snapshot at last update.', max_length=150),
        ),
        migrations.AddField(
            model_name='headcountaudit',
            name='modified_by_name',
            field=models.CharField(blank=True, help_text='Username snapshot.', max_length=150),
        ),
        migrations.AlterField(
            model_name='hourlyplan',
            name='headcount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hourlyplanblock',
            name='reason',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='hourlyplanblock',
            name='slot_time',
            field=models.TimeField(help_text='Slot start time (HH:MM)'),
        ),
    ]
