# Generated by Django 5.2.5 on 2026-05-28 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0008_dailyplan_created_at_dailyplan_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyplan',
            name='created_by_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='dailyplan',
            name='updated_by_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='headcountaudit',
            name='modified_by_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='hourlyplan',
            name='headcount',
            field=models.IntegerField(blank=True, help_text='Per-hour headcount override', null=True),
        ),
    ]
