# Generated by Django 5.2.5 on 2026-07-09 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0009_alter_dailyplan_created_by_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hourlyplanblock',
            name='block_type',
            field=models.CharField(choices=[('lunch', 'Lunch Break'), ('preop', 'Operation Preparation'), ('workfin', 'Work Finalization'), ('chair', 'Chair Time'), ('extra', 'Extra Reason')], max_length=20),
        ),
    ]
