# Generated by Django 5.2.5 on 2026-07-09 22:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_subprocesstype_remove_subprocess_process_type_and_more'),
        ('planning', '0010_alter_hourlyplanblock_block_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyplan',
            name='operator',
            field=models.ForeignKey(blank=True, help_text='Operator running this line for the shift.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operated_daily_plans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hourlyplan',
            name='operator',
            field=models.ForeignKey(blank=True, help_text='Overrides the shift operator for this hour only.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operated_hours', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='dailyplan',
            index=models.Index(fields=['date'], name='planning_da_date_c01750_idx'),
        ),
        migrations.AddIndex(
            model_name='dailyplan',
            index=models.Index(fields=['work_center', 'date'], name='planning_da_work_ce_1fb83c_idx'),
        ),
        migrations.AddIndex(
            model_name='dailyplan',
            index=models.Index(fields=['shift', 'date'], name='planning_da_shift_i_651497_idx'),
        ),
        migrations.AddIndex(
            model_name='dailyplan',
            index=models.Index(fields=['operator'], name='planning_da_operato_a28035_idx'),
        ),
        migrations.AddIndex(
            model_name='hourlyplanblock',
            index=models.Index(fields=['daily_plan', 'slot_time'], name='planning_ho_daily_p_73896d_idx'),
        ),
        migrations.AddIndex(
            model_name='hourlyplanblock',
            index=models.Index(fields=['block_type'], name='planning_ho_block_t_3ab8c6_idx'),
        ),
    ]
