# Generated by Django 5.2.5 on 2026-08-27 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0011_dailyplan_operator_hourlyplan_operator_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyplan',
            name='operator_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='hourlyplan',
            name='operator_name',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
