# Generated by Django 6.0.4 on 2026-05-04 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WindingMachine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='MachineAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('subprocess', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.subprocess')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resources.windingmachine')),
            ],
        ),
    ]
