# Generated by Django 5.2.5 on 2026-05-19 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='machineassignment',
            options={'verbose_name': 'Machine Assignment'},
        ),
        migrations.AlterModelOptions(
            name='windingmachine',
            options={'verbose_name': 'Winding Machine'},
        ),
    ]
